# This file is machine-generated - editing it directly is not advised

[[ATK_jll]]
deps = ["Glib_jll", "Libdl", "Pkg"]
git-tree-sha1 = "4105e33871c2bc7faae456679855c2d89adfdc68"
uuid = "7b86fcea-f67b-53e1-809c-8f1719c154e8"
version = "2.34.1+4"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Bzip2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "03a44490020826950c68005cafb336e5ba08b7e8"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.6+4"

[[Cairo]]
deps = ["Cairo_jll", "Colors", "Glib_jll", "Graphics", "Libdl", "Pango_jll"]
git-tree-sha1 = "d0b3f8b4ad16cb0a2988c6788646a5e6a17b6b1b"
uuid = "159f3aea-2a34-519c-b102-8c37f9878175"
version = "1.0.5"

[[Cairo_jll]]
deps = ["Bzip2_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "c6c9c288df5ad1e6534c9dacd9972482c1eb838c"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.0+5"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "4bffea7ed1a9f0f3d1a131bbcd4b925548d75288"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.10.9"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Reexport"]
git-tree-sha1 = "008d6bc68dea6beb6303fdc37188cb557391ebf2"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.4"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Dbus_jll]]
deps = ["Expat_jll", "Libdl", "Pkg"]
git-tree-sha1 = "533c1f040f7c111d64a8b83c1ef562376ffd889a"
uuid = "ee1fde0b-3d02-5ea6-8484-8dfef6360eab"
version = "1.12.16+2"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Expat_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "0a4e4402a91b0761c1de961f94204da5e306a4f3"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.7+5"

[[FLAC_jll]]
deps = ["Libdl", "Ogg_jll", "Pkg"]
git-tree-sha1 = "cd528d5083a589aab69dc6de73a901efa9d69586"
uuid = "1d38b3a6-207b-531b-80e8-c83f48dafa73"
version = "1.3.3+2"

[[FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[Fontconfig_jll]]
deps = ["Bzip2_jll", "Expat_jll", "FreeType2_jll", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "d130ffccfecaa5f53c9338a76dd165b6c3a4dd5b"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.1+13"

[[FreeType2_jll]]
deps = ["Bzip2_jll", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "720eee04e3b496c15e5e2269669c2532fb5005c0"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.1+4"

[[FriBidi_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "cfc3485a0a968263c789e314fca5d66daf75ed6c"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.5+5"

[[GTK3_jll]]
deps = ["ATK_jll", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "FriBidi_jll", "Glib_jll", "Graphene_jll", "HarfBuzz_jll", "Libdl", "Libepoxy_jll", "Pango_jll", "Pkg", "Wayland_jll", "Xorg_libX11_jll", "Xorg_libXcomposite_jll", "Xorg_libXcursor_jll", "Xorg_libXdamage_jll", "Xorg_libXext_jll", "Xorg_libXfixes_jll", "Xorg_libXi_jll", "Xorg_libXinerama_jll", "Xorg_libXrandr_jll", "Xorg_libXrender_jll", "adwaita_icon_theme_jll", "at_spi2_atk_jll", "gdk_pixbuf_jll", "iso_codes_jll", "xkbcommon_jll"]
git-tree-sha1 = "e44fbdf9ea5f2062b860f27a38841f24c7715aee"
uuid = "77ec8976-b24b-556a-a1bf-49a033a670a6"
version = "3.24.11+3"

[[Gettext_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "922315c1eb4e5072b9994fc47072d0351906fe4c"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.20.1+6"

[[Giflib_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "d47390bd2ca1e5ea4219a7aaedbf76f3ca58fde7"
uuid = "59f7168a-df46-5410-90c8-f2779963d0ec"
version = "5.1.4+1"

[[Glib_jll]]
deps = ["Gettext_jll", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "10f579c2365338cc1773d60faeb6c9f88ea8a7b3"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.59.0+3"

[[Graphene_jll]]
deps = ["Glib_jll", "Libdl", "Pkg"]
git-tree-sha1 = "9d0b534de52582b7f1f044d622b858915dc6b126"
uuid = "75302f13-0b7e-5bab-a6d1-23fa92e4c2ea"
version = "1.10.0+2"

[[Graphics]]
deps = ["Colors", "LinearAlgebra", "NaNMath"]
git-tree-sha1 = "45d684ead5b65c043ad46bd5be750d61c39d7ef8"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "1.0.2"

[[Graphite2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7e4edd2a8848722b0588a154a08fb1990c62d751"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.13+3"

[[Gtk]]
deps = ["Cairo", "Cairo_jll", "Dates", "GTK3_jll", "Glib_jll", "Graphics", "Libdl", "Pkg", "Reexport", "Serialization", "Test", "Xorg_xkeyboard_config_jll", "adwaita_icon_theme_jll", "gdk_pixbuf_jll", "hicolor_icon_theme_jll"]
git-tree-sha1 = "117a09d72b0b46a0a5720c760dd0859cd7639dfc"
uuid = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
version = "1.1.4"

[[HarfBuzz_jll]]
deps = ["Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Gettext_jll", "Glib_jll", "Graphite2_jll", "ICU_jll", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "30237d3202f1d4ad9eda0a53b4272078effc50cd"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.6.1+9"

[[ICU_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "b8de23644ee96884110e8071deed3ff0d2de4d9d"
uuid = "a51ab1cf-af8e-5615-a023-bc2c838bba6b"
version = "67.1.0+1"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JpegTurbo_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "76e28bf35d0c179531b11e254f66bbcc1fd268ca"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.0.1+2"

[[LZO_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9d0c44be3e6d9690b19fa2cddb4c2e4b267ef425"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.0+2"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libepoxy_jll]]
deps = ["Libdl", "Libglvnd_jll", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "2edab6849416951df6866b939c149b07bb001f37"
uuid = "42c93a91-0102-5b3f-8f9d-e41de60ac950"
version = "1.5.4+0"

[[Libffi_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "a30d50f837074b6ab43b81d9dd8be190b40cdd45"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.1+3"

[[Libgcrypt_jll]]
deps = ["Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "6b68e8b88e5eee917427a09d7bf15bd838576ba3"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.5+3"

[[Libglvnd_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_libXext_jll"]
git-tree-sha1 = "30a990af9ce535bcba54d1f23f071a7e714f861e"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version = "1.3.0+1"

[[Libgpg_error_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "83b5c9df3a53a570c8fc2a0d7643a2e30a6a141c"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.36.0+2"

[[Libiconv_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7c36dfe7971e55da03d8f54b67d4b3fb8ee01d63"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.0+6"

[[Libmount_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "ac69889ea9ee389e8bacab1bedc605c25d1ca960"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.34.0+2"

[[Libtiff_jll]]
deps = ["JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "84ad722d8b9c6d3b3ca3a067d1da12b641352584"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.1.0+1"

[[Libuuid_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "90bf54060f5223bf7ac450bb9c56d1334d31d04e"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.34.0+6"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[NaNMath]]
git-tree-sha1 = "c84c576296d0e2fbb3fc134d3e09086b3ea617cd"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.4"

[[Ogg_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "4c3275cda1ba99d1244d0b82a9d0ca871c3cf66b"
uuid = "e7412a2a-1a6e-54c0-be00-318e2571c051"
version = "1.3.4+1"

[[PCRE_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9f6be70c2b80ca004d18a4a38f5724264b4115c0"
uuid = "2f80f16e-611a-54ab-bc61-aa92de5b98fc"
version = "8.42.0+3"

[[Pango_jll]]
deps = ["Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "FriBidi_jll", "Glib_jll", "HarfBuzz_jll", "Libdl", "Pkg"]
git-tree-sha1 = "37918672870fbd48c3da80a19b125782759bede7"
uuid = "36c8627f-9965-5494-a995-c6b170f724f3"
version = "1.42.4+9"

[[Pixman_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "f3515e3d8f4b0fd4df9465d9a79cb478dcd84242"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.38.4+4"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[SDL2_image_jll]]
deps = ["JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pkg", "SDL2_jll", "libpng_jll", "libwebp_jll"]
git-tree-sha1 = "0ff92c66d1c3e99b4be7865ad55a4c38bb4859bf"
uuid = "41f3cfe1-fd11-58ad-8074-b9730c29438b"
version = "2.0.5+1"

[[SDL2_jll]]
deps = ["Libdl", "Libglvnd_jll", "Pkg", "Xorg_libX11_jll", "Xorg_libXScrnSaver_jll", "Xorg_libXcursor_jll", "Xorg_libXext_jll", "Xorg_libXinerama_jll", "Xorg_libXrandr_jll", "alsa_jll"]
git-tree-sha1 = "8481dab174638f861e49bc046c59adc1e0af8c9d"
uuid = "ab825dc5-c88e-5901-9575-1e5e20358fcf"
version = "2.0.12+1"

[[SDL2_mixer_jll]]
deps = ["FLAC_jll", "Libdl", "Pkg", "SDL2_jll", "libvorbis_jll", "mpg123_jll"]
git-tree-sha1 = "d18e37eb4f8137fb616aca7383e06c0348f33f63"
uuid = "7e88e5ca-120e-58e7-9660-b2187fd466c0"
version = "2.0.4+1"

[[SDL2_ttf_jll]]
deps = ["FreeType2_jll", "Glib_jll", "Graphite2_jll", "HarfBuzz_jll", "Libdl", "PCRE_jll", "Pkg", "SDL2_jll", "libpng_jll"]
git-tree-sha1 = "3d1638da5b769a2d2dad27baff15311949e09b95"
uuid = "ca9d4746-8a27-5104-babe-80f83b336947"
version = "2.0.15+1"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SimpleDirectMediaLayer]]
deps = ["ColorTypes", "Libdl", "SDL2_image_jll", "SDL2_jll", "SDL2_mixer_jll", "SDL2_ttf_jll"]
git-tree-sha1 = "f81e641b1479708e54a6181b460874f8d1d2b3ca"
uuid = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"
version = "0.2.1"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[Wayland_jll]]
deps = ["Expat_jll", "Libdl", "Libffi_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "29413c4301a8facf4b0f6a4552977eb71c75ccca"
uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
version = "1.17.0+3"

[[Wayland_protocols_jll]]
deps = ["Libdl", "Pkg", "Wayland_jll"]
git-tree-sha1 = "6bd1d95935f5ae53e86cb8c101f8e820492a7130"
uuid = "2381bf8a-dfd0-557d-9999-79630e7b1b91"
version = "1.18.0+3"

[[XML2_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "ecff6bff03b35d482ad5eb51276d6fc4c823cd39"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.10+2"

[[XSLT_jll]]
deps = ["Libdl", "Libgcrypt_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "8bb981a5c4a7efc799250c46ef757cbfd6c5ba9b"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.33+3"

[[Xorg_libX11_jll]]
deps = ["Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "25ef1a3d04558407fc618797c1340d3703bacb94"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+3"

[[Xorg_libXScrnSaver_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll"]
git-tree-sha1 = "e20cd49b76c75b19943d3763fe8e62566d3b1f4e"
uuid = "41e2f9bb-6422-5ff7-a427-aa949331d861"
version = "1.2.3+2"

[[Xorg_libXau_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9284aed438cb747514ee02170f25c2f9cea91c00"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+3"

[[Xorg_libXcomposite_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXfixes_jll"]
git-tree-sha1 = "84c1610b303d155afdb3df44bf5a54c11662503d"
uuid = "3c9796d7-64a0-5134-86ad-79f8eb684845"
version = "0.4.5+3"

[[Xorg_libXcursor_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXfixes_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "f9e26bb7fe6e1cd7b5fb0ffa959fa3b263723f94"
uuid = "935fb764-8cf2-53bf-bb30-45bb1f8bf724"
version = "1.2.0+3"

[[Xorg_libXdamage_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXfixes_jll"]
git-tree-sha1 = "724acf8dc8fd2f26a91b3e5e572a5259029b973a"
uuid = "0aeada51-83db-5f97-b67e-184615cfc6f6"
version = "1.1.5+3"

[[Xorg_libXdmcp_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "95a233c8cf22e098be956a2fbed9db4ec02eadd0"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+3"

[[Xorg_libXext_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "d160f39dbee0faba7b65d62e8b3af4e508ec36b2"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+3"

[[Xorg_libXfixes_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "c090cd1180e6b1d67541f161bf1eb7a5530d7ba0"
uuid = "d091e8ba-531a-589c-9de9-94069b037ed8"
version = "5.0.3+3"

[[Xorg_libXi_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXfixes_jll"]
git-tree-sha1 = "33d931c90ea05cd9fdbbb40803070b404cc3d413"
uuid = "a51aa0fd-4e3c-5386-b890-e753decda492"
version = "1.7.10+3"

[[Xorg_libXinerama_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll"]
git-tree-sha1 = "df96a770b7e70ff0231ae0c28ef2bbdd24b6fbf3"
uuid = "d1454406-59df-5ea1-beac-c340f2130bc3"
version = "1.1.4+3"

[[Xorg_libXrandr_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "efac36579bc9241e831b43040df5d7cf723c4b97"
uuid = "ec84b674-ba8e-5d96-8ba1-2a689ba10484"
version = "1.5.2+3"

[[Xorg_libXrender_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "97a4104340d745968c78009854ab9369b59d7333"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+3"

[[Xorg_libXtst_jll]]
deps = ["Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXfixes_jll", "Xorg_libXi_jll"]
git-tree-sha1 = "fd7a0d176ec47b1468418c1a6aeb919bb1bb913e"
uuid = "b6f176f1-7aea-5357-ad67-1d3e565ea1c6"
version = "1.2.3+3"

[[Xorg_libpthread_stubs_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "20e2b3ee7eacf9f4f64e5804879b8b12eee436db"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+2"

[[Xorg_libxcb_jll]]
deps = ["Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll"]
git-tree-sha1 = "c1efb50fb6a8c40c45451611fbf93feabe5f9611"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+2"

[[Xorg_libxkbfile_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "7e8d24718d295f5964e0e382718f668c4e74b2fd"
uuid = "cc61e674-0454-545c-8b26-ed2c68acab7a"
version = "1.1.0+3"

[[Xorg_xkbcomp_jll]]
deps = ["Libdl", "Pkg", "Xorg_libxkbfile_jll"]
git-tree-sha1 = "89085968a14091835b5c7c4c939e13e61fbf164e"
uuid = "35661453-b289-5fab-8a00-3d9160c6a3a4"
version = "1.4.2+3"

[[Xorg_xkeyboard_config_jll]]
deps = ["Libdl", "Pkg", "Xorg_xkbcomp_jll"]
git-tree-sha1 = "75e6b06a2cca0cb94a6079827dbc653c28e3a301"
uuid = "33bec58e-1273-512f-9401-5d533626f822"
version = "2.27.0+3"

[[Xorg_xtrans_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "52df68f05a75b81221a1d1420ce4a9c375b29ecc"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+2"

[[Zlib_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "fdd89e5ab270ea0f2a0174bd9093e557d06d4bfa"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+16"

[[Zstd_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "4de91f4313d9e88162d461e282fe3066ab3a3c09"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.4.5+1"

[[adwaita_icon_theme_jll]]
deps = ["Libdl", "Pkg", "hicolor_icon_theme_jll"]
git-tree-sha1 = "b641e8f51f6fd59f15a9b7beb9b1cf4c2c0b31ba"
uuid = "b437f822-2cd6-5e08-a15c-8bac984d38ee"
version = "3.33.92+4"

[[alsa_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "04ec50d2469ab57b512f0edc6bd56cc049daeee4"
uuid = "45378030-f8ea-5b20-a7c7-1a9d95efb90e"
version = "1.2.1-1+1"

[[at_spi2_atk_jll]]
deps = ["ATK_jll", "Libdl", "Pkg", "XML2_jll", "Xorg_libX11_jll", "at_spi2_core_jll"]
git-tree-sha1 = "c6d6e687fc00134acbeae3ba51203be895196a39"
uuid = "de012916-1e3f-58c2-8f29-df3ef51d412d"
version = "2.34.1+3"

[[at_spi2_core_jll]]
deps = ["Dbus_jll", "Glib_jll", "Libdl", "Pkg", "Xorg_libXtst_jll"]
git-tree-sha1 = "2410a457fb0c800a6c9ded4ae45d4a71abba823e"
uuid = "0fc3237b-ac94-5853-b45c-d43d59a06200"
version = "2.34.0+3"

[[gdk_pixbuf_jll]]
deps = ["Glib_jll", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pkg", "Xorg_libX11_jll", "libpng_jll"]
git-tree-sha1 = "43a37ec94ceb49875d23114bf79b2cffe537fea6"
uuid = "da03df04-f53b-5353-a52f-6a8b0620ced0"
version = "2.38.2+8"

[[hicolor_icon_theme_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "f2c47ff27831f0404b621ee4bce3705d433b6f78"
uuid = "059c91fe-1bad-52ad-bddd-f7b78713c282"
version = "0.17.0+2"

[[iso_codes_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "94d3e2266976ed7193376a64aeea6540e9ecb7e3"
uuid = "bf975903-5238-5d20-8243-bc370bc1e7e5"
version = "4.3.0+3"

[[libpng_jll]]
deps = ["Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "0a93f3eae5b80f08dc789e549657c199f1da6417"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.37+5"

[[libvorbis_jll]]
deps = ["Libdl", "Ogg_jll", "Pkg"]
git-tree-sha1 = "8014e1c1033009edcfe820ec25877a9f1862ba4c"
uuid = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a"
version = "1.3.6+5"

[[libwebp_jll]]
deps = ["Giflib_jll", "JpegTurbo_jll", "Libdl", "Libglvnd_jll", "Libtiff_jll", "Pkg", "libpng_jll"]
git-tree-sha1 = "ba19e70487d21c0c9224869d5be92498f1b9fae8"
uuid = "c5f90fcd-3b7e-5836-afba-fc50a0988cb2"
version = "1.1.0+0"

[[mpg123_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "f78f01d2bf6a5e97afdab9ae7c862c41e1e9d86a"
uuid = "3205ef68-7822-558b-ad0d-1b4740f12437"
version = "1.25.12+0"

[[xkbcommon_jll]]
deps = ["Libdl", "Pkg", "Wayland_jll", "Wayland_protocols_jll", "Xorg_libxcb_jll", "Xorg_xkeyboard_config_jll"]
git-tree-sha1 = "48e08959222ca822d16d9ffa6777caebce951469"
uuid = "d8fb68d0-12a3-5cfd-a85a-d49703b185fd"
version = "0.9.1+3"
